bluek8s/kubedirector

- deploy/kubedirector/crd-cluster.yaml
> correct role-id property name

- README.md
> Fix Readme build status.

- pkg/validator/cluster.go
> allow omitting role spec if "zero members" is legal

- pkg/executor/guest.go
- pkg/reconciler/members.go
This PR is  to resolve Issue #19
> Enhance IsFileExists function to return error as well as boolean

- pkg/executor/guest.go
- pkg/reconciler/members.go
Put the member into config_error state.
For issue #73.
> error if can't execute IsFileExists or ReadFile

- Makefile
- deploy/kubedirector/crd-app.yaml
- pkg/shared/util.go
- pkg/validator/app.go
- pkg/validator/cluster.go
- pkg/validator/types.go
> additional validation for app & cluster CRs

- doc/virtual-clusters.md
> docs update for shortnames, events, and service labels

- deploy/example_config/cr-config-eks.yaml
- doc/quickstart.md
An example config file and some additional notes in the "quickstart".
> Amazon EKS support

- HISTORY.md
Start working on the change list for the 0.2.0 release.
> add a history file

- Makefile
- doc/gke-notes.md
- doc/quickstart.md
The additional text in gke-notes explains why.
> wait for teardown to succeed

- HISTORY.md
- README.md
- doc/quickstart.md
Will probably continue until release!
> still doc-tweakin'

- Makefile
addresses issue #134
Previously "make deploy" would wait for the container to start responding to "kubectl logs" and then go ahead and create the example catalog.
Now it waits for the pod, then waits for the KubeDirector process to create the admission control webhook, then creates the example catalog.
This gets rid of a race window I've hit where an example catalog entry got created before the admission control was set up.
> deploy should wait for webhook

- HISTORY.md
- README.md
> new public Slack invite

- pkg/reconciler/members.go
issue #146 
Rather than just checking to see if roleStatus is nil, we can check to see if there are zero ready members. This similarly handles the zero-members case but will also skip non-zero-members roles that are entirely made up of non-ready members. In that case we also don't need to bother finding the setup package URL.
> prevent crash when scaling role

- HISTORY.md
- doc/quickstart.md
Re-creating this branch so that the release will take on the fix for issue #146.
> 0.2.0 release info

- Makefile
This should get rid of the errors we were seeing on macos. @swamibluedata @joel-bluedata
> Makefile doesn't have sed errors on macos now.

- pkg/executor/service.go
- pkg/reconciler/services.go
- pkg/reconciler/types.go
> handle zero-ports services

- Makefile
- README.md
- deploy/example_config/eks-gp2-for-kd.yaml
- doc/eks-notes.md
- doc/quickstart.md
> documentation and minor Makefile changes for EKS support

- .travis.yml
- cmd/manager/main.go
- pkg/catalog/configmeta.go
- pkg/catalog/interrogate.go
- pkg/controller/kubedirectorcluster/cluster.go
- pkg/controller/kubedirectorcluster/kubedirectorcluster_controller.go
- pkg/controller/kubedirectorcluster/members.go
- pkg/controller/kubedirectorcluster/roles.go
- pkg/controller/kubedirectorcluster/services.go
- pkg/controller/kubedirectorconfig/kubedirectorconfig_controller.go
- pkg/executor/cluster.go
- pkg/executor/guest.go
- pkg/executor/service.go
- pkg/executor/statefulset.go
- pkg/executor/volume.go
- pkg/observer/observer.go
- pkg/shared/client.go
- pkg/shared/types.go
- pkg/validator/app.go
- pkg/validator/cluster.go
- pkg/validator/kdsettings.go
- pkg/validator/server.go
- pkg/validator/types.go
- pkg/validator/util.go
> Access client via global handle rather than arg passed everywhere.

- pkg/controller/kubedirectorcluster/cluster.go
- pkg/controller/kubedirectorcluster/kubedirectorcluster_controller.go
- pkg/executor/cluster.go
- pkg/executor/service.go
- pkg/executor/statefulset.go
- pkg/shared/logging.go
Simplified the update retry code and added comments to reference the newly created GitHub issue on this topic.
https://github.com/bluek8s/kubedirector/issues/194
> GitHub issue #178: harden object-update behavior

- deploy/kubedirector/deployment-prebuilt.yaml
Bring the YAML into sync with the new operator SDK's generated YAML.
> fix prebuilt deployment

- .travis.yml
- Makefile
- cmd/manager/main.go
- pkg/apis/kubedirector.bluedata.io/v1alpha1/kubedirectorconfig_types.go
- pkg/controller/add_kubedirectorcluster.go
- pkg/controller/add_kubedirectorconfig.go
- pkg/controller/controller.go
- pkg/controller/doc.go
- pkg/controller/kubedirectorcluster/cluster.go
- pkg/controller/kubedirectorcluster/kubedirectorcluster_controller.go
- pkg/controller/kubedirectorcluster/roles.go
- pkg/controller/kubedirectorcluster/services.go
- pkg/controller/kubedirectorconfig/doc.go
- pkg/controller/kubedirectorconfig/kubedirectorconfig_controller.go
- pkg/executor/cluster.go
- pkg/executor/service.go
- pkg/observer/observer.go
- pkg/validator/cluster.go
- pkg/validator/server.go
Some cleanup that happened during work to bring in a controller for another resource type.
Mostly this is formatting, fixing comments, and making some generic var/function names more specific.
I fixed a bug in the validator in the case where there is a CRD in our namespace that doesn't have a validator function defined for it.
For service update, I removed a redundant log message and fixed the arguments to another couple of args.
I also switched the argument order for GetSecret to be consistent with the other getters.
> some cleanup

- pkg/controller/kubedirectorcluster/cluster.go
- pkg/controller/kubedirectorconfig/config.go
addresses issue #207
In the previous form of the operator framework, where the framework would deliver the CR contents to the reconcile handler as an argument, we had to check the incoming status UID to protect against the following case: a reconcile invocation (usually just from a periodic poll) was queued up right as we were making changes to the CR in a current handler, so the CR delivered to the next handler would then not contain the changes we made.
In the new operator framework we didn't think we needed this. Each handler fetches the CR when it starts running, through the controller-runtime client. That client does some caching but we believed that it was guaranteed that when we do a PUT in one handler followed by a GET in a later handler, the GET would show the results of the PUT. …
> reinstate "stale CR protection"

- HISTORY.md
- deploy/example_catalog/cr-app-cassandra-3.11.json
- deploy/example_catalog/cr-app-cdh5142cm.json
- deploy/example_catalog/cr-app-spark221e2.json
- pkg/executor/statefulset.go
Swami, bringing in a couple of your changes here.
> misc persist dirs improvements

- deploy/kubedirector/kubedirector_v1alpha1_kubedirectorcluster_crd.yaml
- deploy/kubedirector/kubedirector_v1alpha1_kubedirectorconfig_crd.yaml
- pkg/apis/kubedirector.bluedata.io/v1alpha1/kubedirectorcluster_types.go
- pkg/apis/kubedirector.bluedata.io/v1alpha1/kubedirectorconfig_types.go
- pkg/controller/kubedirectorcluster/kubedirectorcluster_controller.go
- pkg/controller/kubedirectorcluster/members.go
- pkg/controller/kubedirectorcluster/types.go
- pkg/shared/globalconfig.go
- pkg/validator/cluster.go
- pkg/validator/types.go
For review purposes, probably easiest to examine each commit independently.
> grab bag of loose ends for the v0.3 release

- HISTORY.md
- doc/kd-release-process.md
- doc/quickstart.md
- version/version.go
Starting the [release process](https://github.com/bluek8s/kubedirector/blob/master/doc/kd-release-process.md) for 0.3.0.
> 0.3.0 release info

- Makefile
- deploy/kubedirector/deployment-prebuilt.yaml
- doc/app-authoring.md
- doc/quickstart.md
- doc/virtual-clusters.md
- version/version.go
Continuing the release process for 0.3.0.
> 0.3.0 release point

- pkg/executor/service.go
Need this for some reverse-DNS-lookup cases.
> set PNRA for headless service too

- deploy/example_catalog/cr-app-tensorflow-notebook.json
- deploy/example_clusters/cr-cluster-tensorflow-notebook.yaml
A jupyter notebook app  with TF 1.14.0, Keras, and other essential AI/ML packages. An exhaustive list of installed packages is obtained using `conda list`.
> Add jupyter notebook with Tensorflow

- pkg/controller/kubedirectorcluster/members.go
- pkg/executor/service.go
- pkg/validator/types.go
See individual commit descriptions.
> misc minor changes

- pkg/executor/statefulset.go
https://github.com/bluek8s/kubedirector/issues/230
configcli requires /usr and /opt. So these two have to be part of persistent storage as well.
When creating default volume mounts, detect if app config is present for a member and setup 3 folders instead of just 1 (/etc)
> Add additional persistdirs when app config is present

- deploy/kubedirector/kubedirector_v1alpha1_kubedirectorapp_crd.yaml
- deploy/kubedirector/kubedirector_v1alpha1_kubedirectorcluster_crd.yaml
It's the same value type as any other resource.
Issue #247
> better GPU resource typing in CRDs

- doc/quickstart.md
Don't need root user container anymore.
> docs micro-tweak

- deploy/example_catalog/cr-app-centos7.json
- pkg/executor/statefulset.go
> persistence fix

- Makefile
- deploy/kubedirector/deployment-prebuilt.yaml
- doc/app-authoring.md
- doc/quickstart.md
- doc/virtual-clusters.md
- version/version.go
Note that we still reference the wiki docs for the 0.3.1 data types.
> 0.3.2 release point

- deploy/kubedirector/deployment-prebuilt.yaml
- deploy/operator.yaml
- doc/quickstart.md
> make liveness probe optional

- pkg/executor/statefulset.go
> another persistent storage fix

- Makefile
I think these loops are just slowing down the `make` commands. GOTTA GO FAST.
> We don't need these loops. Replace with a single command.

- deploy/example_catalog/cr-app-centos8.json
- deploy/example_clusters/cr-cluster-centos8-stor.yaml
- deploy/example_clusters/cr-cluster-centos8.yaml
Created docker image using Docker file. 
Pushed docker image to Docker hub.
Added yaml files for Kubedirector Centos 8x app and cluster deployment
> Added yaml files for Kubedirector Centos 8x app and cluster deployment

- deploy/example_catalog/cr-app-ubuntu18.04.json
- deploy/example_clusters/cr-cluster-ubuntu18.04-stor.yaml
- deploy/example_clusters/cr-cluster-ubuntu18.04.yaml
Added Ubuntu 18.04 KD app json file.
Added Ubuntu 18.04 KD cluster yaml file.
Added Ubuntu 18.04 KD cluster with persitent storage yaml file
> Added yaml files for KD Ubuntu 18.04 app and cluster deployment

- deploy/example_catalog/cr-app-cassandra-3.11.json
- deploy/example_catalog/cr-app-cdh5142cm.json
- deploy/example_catalog/cr-app-centos7.json
- deploy/example_catalog/cr-app-spark221e2.json
- deploy/kubedirector/kubedirector.hpe.com_kubedirectorapps_crd.yaml
- pkg/apis/kubedirector/v1beta1/kubedirectorapp_types.go
- pkg/controller/kubedirectorcluster/members.go
- pkg/validator/app.go
Github issue: https://github.com/bluek8s/kubedirector/issues/273
> BDP 930 changes

- deploy/example_catalog/cr-app-cdh632cm.json
- deploy/example_clusters/cr-cluster-cdh632cm-stor.yaml
Created example app definition json file and cluster json file for creating a sample cluster.
> add app definition json file and cluster yaml file for cdh 6.3.2

- pkg/controller/kubedirectorcluster/cluster.go
fixes #312 
If we get an error in syncMemberServices (causing handler exit), we lose the necessary update to SpecGenerationToProcess.
Easiest way to trigger this is to run KD in an environment like GKE using LoadBalancer services that can take a while to delete. Create a cluster with a large number of role members, then edit the cluster to shrink that role to its minimum, then immediately edit the cluster again to size the role up again. Because the old services are still being deleted and we want to re-use the same service names, reconciliation will fail until the old services finish deleting.
We should set SpecGenerationToProcess as soon as we know we should. Right after syncClusterRoles should be good, since the "state" from that function is what we would be worried about losing an an …
> set SpecGenerationToProcess earlier

- pkg/catalog/configmeta.go
https://github.com/bluek8s/kubedirector/issues/317
> Make changes to skip roles which do not have any members.

- deploy/example_catalog/cr-app-spark245.json
- deploy/example_clusters/cr-cluster-spark245-stor.yaml
- deploy/example_clusters/cr-cluster-spark245.yaml
Apache Spark 2.4.5 having following package and tools,
* Jupyterhub version - 1.1.0 with Jupyterlab.
* Python 3.6.0 |Anaconda3
* R version latest with libraries - sparklyr, devtools, knitr, tidyr, ggplot2, shiny
* R Hadoop client for accessing HDFS from R - rHadoopClient_0.2.tar.gz,
* Jupyterhub with spark magic kernels - Scala, PySpark, SQL
* Sparkling water 3.3.0
* Livy server
> Application Json and cluster yaml files for apache Spark 2.4.5 with Jupyterhub 

- deploy/example_catalog/cr-app-elk771.json
- deploy/example_clusters/cr-cluster-elk771.yaml
Added app json and cluster yaml files for ELK 7.7.1
It contains 4 roles:
1) Master(Mandatory having cardinality of 1)
2) Data(Optional having cardinality of 0+)
3) Logstash(Optional having cardinality of 0+)
4) Kibana(Optional having cardinality of 0+)
and 3 services:
1) Elasticsearch
2) Kibana
2) Logstash
> app json and cluster yaml files for ELK 7.7.1

- deploy/example_catalog/cr-app-elk771.json
Mistakenly had checked in incorrect app json for ELK stack. Corrected it by removing elasticsearch and adding data to selectedRoles.
> remove elasticsearch and add data to selectedRoles for ELK

- deploy/example_catalog/cr-app-mapr610-secured.json
- deploy/example_catalog/cr-app-mapr610-unsecured.json
- deploy/example_clusters/cr-cluster-mapr610-unsecured.yaml
- deploy/example_clusters/cr-cluster-mapr610.yaml
this change is against the issue
https://github.com/bluek8s/kubedirector/issues/340
fixed by modifying json file of unsecured KD MapR app
> Updated distroID of unsecured KD MapR app

- deploy/example_catalog/cr-app-spark245.json
Fixed #335 for kd-Spark245.
Reference PR for catalog:
https://github.com/bluedatainc/bluedata-catalog/pull/388
> service not auto start after delete the pod #335

- deploy/example_catalog/cr-app-spark245.json
- deploy/example_clusters/cr-cluster-spark245-stor.yaml
- deploy/example_clusters/cr-cluster-spark245.yaml
Spark245 Application Json file - Mapped to bluedata/spark245:1.6, this image is having 'Jupyterhub LDAP Authenticator feature'.
Spark245 Cluster yaml files - having input details for Jupyterhub LDAP Authentication.
https://github.com/bluedatainc/bluedata-catalog/pull/382
> Spark245 - LDAP authentication support for jupyterhub

- pkg/validator/cluster.go
- pkg/validator/types.go
If the storage stanza is specified, the size must be > 0. Otherwise the statefulset controller will freak out.
> BDP Issue 353

- deploy/kubedirector/kubedirector.hpe.com_kubedirectorapps_crd.yaml
This closes the above mentioned issue. Make sure that all the configMeta values are string and reject if they are not.
> BDP Issue 27

- deploy/example_catalog/cr-app-mapr610-secured.json
- deploy/example_catalog/cr-app-mapr610-unsecured.json
There was change in the connections design and had to update the MapR code to accommodate the changes. A new docker file was uploaded and respective version has been updated in these JSON files.
> Updated KD-MapR JSON file

- deploy/example_catalog/cr-app-centos8.json
- deploy/example_catalog/cr-app-ubuntu18.04.json
2 JSON file had docker.io and so removed them.
> removing docker.io from JSON file

- deploy/example_catalog/cr-app-deployment-engine.json
- deploy/example_catalog/cr-app-jupyter-notebook.json
- deploy/example_catalog/cr-app-tensorflow-gpu-dockerhub.json
- deploy/example_catalog/cr-app-training-engine.json
- deploy/example_clusters/cr-cluster-tensorflow-gpu-dockerhub.yaml
Following changes are made:
- Change image name
- Add a fixed image tag
- Change the name of tensorflow image from dockerhub
- Rename `kd-flask_serving` to `kd-api-serving`
I'll push the image with approved names and tags once reviewed.
> Update image metadata

- deploy/example_catalog/docs/cdh632-readme.md
cdh632-readme.md provides a brief on cdh632 kd cluster app, roles, sample test cases and relevant links.
> Added cdh632 readme

- deploy/example_catalog/docs/elk771-readme.md
elk771-readme.md provides a brief on elk771 kd cluster app, roles, sample test cases and relevant links.
> Added elk771 readme

- deploy/example_catalog/cr-app-mapr610-secured.json
- deploy/example_catalog/cr-app-mapr610-unsecured.json
- deploy/example_catalog/docs/mapr610-readme.md
- deploy/example_clusters/cr-cluster-mapr610-unsecured.yaml
- deploy/example_clusters/cr-cluster-mapr610.yaml
Hi,
KD MapR app has been updated to have generic license and so the dockerfile version was bumped. So had to change the JSON file to match the latest docker image version.
Also added a document on what features are added in the app and how to use the app with some sample programs.
> Updating MapR docker version in JSON file and added document for the App

- deploy/example_catalog/docs/spark245-with-jupyterhub-readme.md
Updated spark245-with-jupyterhub-readme.md
with, 
docker image location
docker pull command
> Updated spark245-with-jupyterhub-readme.md

- deploy/example_catalog/docs/centos8-readme.md
- deploy/example_catalog/docs/kafka55-readme.md
- deploy/example_catalog/docs/ubuntu18-readme.md
Added docker image location section for Kafka. Added new documentation files for centos8 and ubuntu18 with just the section for docker image location
> Added docker image location section for Kafka, centos8 and ubuntu18

- deploy/example_catalog/docs/cdh632-readme.md
- deploy/example_catalog/docs/elk771-readme.md
Updated KD CDH and ELK with Dockerfile location and docker pull command in respective docs
> update cdh and elk with dockerfile locations and docker pull command

- deploy/example_catalog/cr-app-spark245.json
- deploy/example_clusters/cr-cluster-spark245-stor.yaml
- deploy/example_clusters/cr-cluster-spark245.yaml
Spark 245 - updated with SSSD support, updated AD and LDAP login support with hpecp-ext-auth-secret
Spark245 is updated with following details,
newer version of Livy server,
Hadoop client.
enhanced Jupyterhub with LDAP and AD log-in support
sssd enabled.
> Spark 245 - updated with SSSD support, updated AD and LDAP login support with hpecp-ext-auth-secret

- deploy/example_catalog/cr-app-jupyter-notebook.json
> update jupyter notebook image tag

- deploy/example_catalog/cr-app-jupyter-notebook.json
- deploy/example_catalog/docs/jupyter-notebook-readme.md
Updates to allow PIP install by notebook user.
Also removed unwanted directory from persistent disk list
> Updates to allow PIP install by notebook user.

- deploy/example_catalog/cr-app-spark245.json
(BDP-2703) the hpe proxy is being set in the spark245 image
> Fixed - (BDP-2703) the hpe proxy is being set in the spark245 image 

- deploy/example_catalog/cr-app-cassandra-3.11.json
- deploy/example_catalog/cr-app-gitlab-ee.json
Add logos for Cassandra and Gitlab Apps
> Add Cassandra and Gitlab logos

- deploy/example_catalog/docs/jupyter-notebook-readme.md
Documentation added/updated :
1. Usage details.
2. Notes on support.
3. Docker image version update.
> Documentation Update: Usage details for KD MLOps notebook and docker image version update

- deploy/example_catalog/cr-app-jupyter-notebook.json
Update Jupyter Notebook Image version to the latest
> Update Notebook Image version

- deploy/example_catalog/docs/dfcompute610-readme.md
- deploy/example_clusters/cr-cluster-datafabric610.yaml
I updated the document for cross cluster connection
> DfCompute app: Updated documentation for cross cluster connection

- deploy/example_clusters/cr-cluster-datafabric610.yaml
Updated documentation in datafabric cluster yaml.
> update doc for datafabric cluster yaml

- deploy/example_catalog/docs/spark245-with-jupyterhub-readme.md
Updated with Spark v2.4.5 with Jupyterlab Kubedirector Application usage details.
> Updated readme file for spark245

- deploy/example_catalog/cr-app-deployment-engine.json
- deploy/example_catalog/cr-app-jupyter-notebook.json
- deploy/example_catalog/cr-app-mlflow.json
- deploy/example_clusters/cr-cluster-mlflow.yaml
updated bluedata images:
- kd-notebook:1.14
- kd-api-serving:1.4 (for deployment) 
- kd-mlflow:1.2
added a cr for mlflow
> updated kd app image versions and added a new cr yaml

- deploy/example_catalog/cr-app-mlflow.json
Update mlflow version to 1.3,  https://github.hpe.com/hpe/bluedata-catalog/pull/607/files
> update mlflow app version to 1.3 | mlflow service enhancements

- HISTORY.md
- doc/quickstart.md
- version/version.go
also backfilling some missing entries in HISTORY.md
> prep release info

- CONTRIBUTING.md
- README.md
- ROADMAP.md
- doc/kubedirector-development.md
Still open to roadmap changes; putting this PR up so that folks can see it.
> fix some docs-rot and add a roadmap

- deploy/example_clusters/cr-cluster-centos7.yaml
- deploy/kubedirector/kubedirector.hpe.com_kubedirectorclusters_crd.yaml
- deploy/kubedirector/rbac-default.yaml
- pkg/apis/kubedirector/v1beta1/kubedirectorcluster_types.go
- pkg/executor/statefulset.go
- pkg/observer/observer.go
- pkg/validator/cluster.go
- pkg/validator/server.go
Fix https://github.com/bluek8s/kubedirector/issues/475
> Ability to provide Service Account at KDCluster level

- pkg/validator/cluster.go
https://github.com/bluek8s/kubedirector/issues/515
> Add Extra values from authenticator to subject access review

- Makefile
This check was added recently without the leading "@".
> reduce deploy verbosity

- Makefile
> explicitly delete webhook in teardown

- pkg/executor/statefulset.go
- pkg/executor/types.go
> get rid of deprecated method for setting PVC storage class

- pkg/executor/statefulset.go
- pkg/executor/types.go
This is initial PR to implement the feature. Testing and polishing the code is in progress
> Report progress for persistent data init

- pkg/validator/server.go
- pkg/validator/util.go
closes #505 
closes #568 
Cf. the individual commit comments.
> webhook tweaks

- pkg/executor/statefulset.go
- pkg/executor/types.go
Comments are polished. We check all the options that are used for rsync
> Report progress for persistent data init (Minor updates).

- deploy/example_catalog/cr-app-jupyter-notebook.json
Adding the persistent dirs as seen in everest 5.4.1 cr (https://github.hpe.com/hpe/everest/blob/release/5.4.1/kubernetes/addons/kubedirector/templates/mlops-crs/cr-app-jupyter-notebook.json)  and updating the image to 3.2.
> Update notebook version to 3.2

- deploy/kubedirector/kubedirector.hpe.com_kubedirectorclusters_crd.yaml
- pkg/apis/kubedirector/v1beta1/kubedirectorcluster_types.go
- pkg/controller/kubedirectorcluster/cluster.go
Resolves https://github.com/bluek8s/kubedirector/issues/596
> Added MemberUpgrading and MemberRollingBack fields to MemberStateRollup

- pkg/apis/kubedirector/v1beta1/kubedirectorapp_types.go
- pkg/validator/app.go
- pkg/validator/cluster.go
Resolves https://github.com/bluek8s/kubedirector/issues/592
> Add ability to set Spec.Upgradable field to in-use KD apps

- pkg/validator/cluster.go
- pkg/validator/types.go
Resolves https://github.com/bluek8s/kubedirector/issues/591
> Ezml 1127 check app difference

- deploy/kubedirector/kubedirector.hpe.com_kubedirectorclusters_crd.yaml
- pkg/apis/kubedirector/v1beta1/kubedirectorcluster_types.go
- pkg/controller/kubedirectorcluster/cluster.go
- pkg/controller/kubedirectorcluster/members.go
- pkg/controller/kubedirectorcluster/roles.go
Made rollback process more stable.
Eliminated UpgradeMembersCount field
> Ezml 1747 correct rollback process
