pkg/reconciler/cluster.go, pkg/reconciler/members.go, pkg/reconciler/roles.go, pkg/reconciler/services.go, pkg/reconciler/types.go
This addresses issue #22 in an implicit way. 
- Create a new member state called memberConfigError. If any of the configuration process (creating config meta, injecting bdvcli or setting up appconfig) fails, member state will be put into memberConfigError.
- cluster will be put into warning state if one or more member is in memberConfigError stat
- for rest of the code, memberConfigError is treated similar to memberReady
=> Handle config errors properly instead of retrying

cmd/kubedirector/main.go, pkg/executor/guest.go, pkg/reconciler/members.go, pkg/reconciler/roles.go, pkg/reconciler/types.go
This addresses issue #64.
Now we won't occupy a handler while a startscript is running, at least not for initial configuration. Add/del notifies are still synchronous.
One consequence of this is that we have to be careful that we don't make changes to the set of cluster members while an initial config is running on some member. That member will have some idea of the current member set, and it's not yet in a state where it can receive notifies.
Another consequence is that the completion of initial configs can be staggered somewhat across members, if they take a noticeably different amount of time to run. Previously if you had nodes A, B, and C all entering "creating" state together, they would all finish together (as long as they all succeeded). Now however let's say A and B finish first, …
=> run initial config asynchronously

deploy/kubedirector/crd-app.yaml, pkg/apis/kubedirector.bluedata.io/v1alpha1/types.go, pkg/apis/kubedirector.bluedata.io/v1alpha1/zz_generated.deepcopy.go, pkg/catalog/interrogate.go, pkg/executor/statefulset.go
This is to address issue #29 
- Add --parent option to init Container "cp" command so non-top level directories can be supported.
- Add role based persist_dirs which will override any top level persist_dirs
- When creating the statefulset spec for volume claims, ignore any subdirectories that are already covered by default mounts.
=> persist_dirs related changes/fixes

Makefile, pkg/reconciler/cluster.go
issue #40 
- Add backoff for retries.
- Bail out if object is going away or has gone away.
=> improvements for status-write-retry

.travis.yml
This check proved to be too fragile to be useful.
Removing this check to improve project velocity.
=> Remove fragile check.

Makefile
During initialization, a headless service is created by operator sdk for tracking metrics. This doesn't have any ownerReference pointing back to our deployment. So on teardown this service is left behind. Ideally we want to do a merge patch to update the Service. k8s is not letting us do a merge patch on "/metadata/ownerReferences". Tried both add and replace.
So instead, just adding an explicit delete service on teardown
=> delete headless service on teardown

Makefile
I was working from a new (Ubuntu-derived) system and came across this issue. Some of the shell snippets use bash-ish syntax... which is apparently supported OK in the macOS "sh" and on some other systems' "sh", but not on this one.
One fix would be to change all the syntax to make sure it is strictly sh-compatible... but I think it's also legit just to request bash. Let me know what you guys think.
=> ensure that shell snippets use bash

Makefile, pkg/reconciler/cluster.go, pkg/reconciler/handler.go, pkg/reconciler/types.go, pkg/reconciler/util.go, pkg/validator/app.go, pkg/validator/cluster.go, pkg/validator/util.go
Addresses issue #7 (and #89, see below).
This change adds another map in the handler state, which associates a "cluster key" (namespace+name) to the app ID used by that cluster. We're going to use that in-memory object to track when a KubeDirectorApp is referenced by any KubeDirectorCluster, and prevent app delete/modify in that situation. The functions that reference the map have a bit more commentary about why that data structure is used.
Note that if you want to try out this branch, you'll probably want to set your Local.mk to deploy from my bluek8s/kubedirector:joel-dev image. Because this changes the webhook properties it's not easy to get it running correctly just by using "make redeploy" after deploying from the normal image.
----------
Adding the above-mentioned map to the handler …
=> don't allow app delete/modify while in use

Makefile
"make compile" was introduced as a new target at the top of the file at one point, but really we want "make build" to be the thing that happens if someone just types "make".
=> have "make build" be the default again

deploy/example_catalog/cr-app-cassandra-3.11.json, deploy/example_catalog/cr-app-cdh5142cm.json, deploy/example_catalog/cr-app-centos7.json, deploy/example_catalog/cr-app-spark221e2.json, deploy/example_catalog/cr-app-tensorflowcpu.json, deploy/kubedirector/crd-app.yaml, pkg/apis/kubedirector.bluedata.io/v1alpha1/types.go, pkg/apis/kubedirector.bluedata.io/v1alpha1/zz_generated.deepcopy.go, pkg/validator/app.go
Since these behave differently than the per-role props in certain ways -- they act only as defaults during CR create and are then removed -- let's rename them to mark them as such.
=> change names of top-level default image/package props

pkg/validator/cluster.go
If the value specified in the config was something other than "standard", this check was not working as desired. We should be checking whatever default is specified in the config here (rather than always checking "standard").
=> fix validation for storageclassname default

HISTORY.md, README.md, doc/quickstart.md
Abbreviated version of the release process is described below FYI. This branch will NOT be merged to master quite yet.
Before Monday:
- The 0.2.0-release branch will be created from this branch. Various changes there e.g. the 0.2.0 tag for the prebuilt image, links to v0.2.0 versions of docs/wiki, etc.
- Create the prebuilt image and regression test.
Assuming everything goes well, then on Monday:
- Tag the 0.2.0-release branch as v0.2.0. Don't merge it to master.
- Advertise the release: merge the 0.2.0-release-info branch to master and promote the v0.2.0 tag into a "release" on the releases page.
- Delete both branches.
=> prepare for 0.2.0 release

HISTORY.md, doc/quickstart.md
Modifying the docs on master to indicate that [0.2.0](https://github.com/bluek8s/kubedirector/releases/tag/v0.2.0) is the latest release.
=> advertise the 0.2.0 release

Makefile
Remove the `make clean` output from the `make check-format` output. Just pipe it to `/dev/null` since we don't want it.
Previously:
Previously, with error:
Now:
Now, with error:
=> Send stdout to /dev/null because we don't care about it.

Makefile, cmd/kubedirector/main.go
- Change sdk.Watch to add support for all namespaces for cluster cr
Config CR and App CR will still have to be deployed in the same namespace where kubedirector is running from.
- Change Makefile to delete kubedirectorclusters from all namespace during teardown
=> Multiple Namespace watch support

pkg/validator/cluster.go
This fixes a compile-warning in this file noted during development.
Signed-off-by: Anne Marie Merritt <amm@bluedata.com>
=> Nit:  Fixed print datatype to reference the correct definition.

deploy/kubedirector/kubedirector_v1alpha1_kubedirectorcluster_crd.yaml, pkg/apis/kubedirector.bluedata.io/v1alpha1/kubedirectorcluster_types.go, pkg/apis/kubedirector.bluedata.io/v1alpha1/zz_generated.deepcopy.go, pkg/controller/kubedirectorcluster/roles.go, pkg/executor/statefulset.go, pkg/validator/cluster.go
I believe the new operator-sdk schema validator was getting confused because Role.Storage is an optional property but it was a struct and not a pointer. The same goes for ClusterStorage.Size. I made Role.Storage a pointer and it resolved the issue.
=> Fix issue where storage.size KDC property is always required.

cmd/manager/main.go, pkg/validator/kdsettings.go
Restore namespace watch behavior prior to new operator SDK migration.
- KD watches ALL namespaces for KDC objects.
- KD watches only ITS OWN namespace for KD Config object.
=> Investigate namespace watch behavior with new operator SDK #177 

build/Dockerfile
Add ps and killall utilities to ubi-minimum image so that make redeploy works again.
=> Issue 184: "make redeploy" broken with ubi-minimal base image 

Gopkg.lock, Makefile, build/Dockerfile, deploy/example_catalog/cr-app-cassandra-3.11.json, deploy/example_catalog/cr-app-cdh5142cm.json, deploy/example_catalog/cr-app-centos7.json, deploy/example_catalog/cr-app-spark221e2.json, deploy/example_catalog/cr-app-tensorflowcpu.json, deploy/example_catalog/cr-app-tensorflowgpu.json, deploy/kubedirector/kubedirector_v1alpha1_kubedirectorapp_crd.yaml, deploy/kubedirector/kubedirector_v1alpha1_kubedirectorcluster_crd.yaml, deploy/kubedirector/kubedirector_v1alpha1_kubedirectorconfig_crd.yaml, doc/app-authoring.md, pkg/apis/kubedirector.bluedata.io/v1alpha1/decode.go, pkg/apis/kubedirector.bluedata.io/v1alpha1/kubedirectorapp_types.go, pkg/apis/kubedirector.bluedata.io/v1alpha1/kubedirectorcluster_types.go, pkg/apis/kubedirector.bluedata.io/v1alpha1/kubedirectorconfig_types.go, pkg/controller/kubedirectorcluster/types.go, pkg/validator/app.go, pkg/validator/types.go
This follows the style guide for Kubernetes resource properties, and "kubectl describe" works best with camelCased names. So let's bite the bullet.
One bullet not bitten here however is the naming scheme for the config data seen inside the container by config CLI. Changing those property names, although possibly nice for consistency with some parts of the CRs, would require also changing config CLI and app startscripts. I'm not sure if we want to do that, and even if we do, let's not bundle it into this change here.
=> camelCase our CR property names

.travis.yml
Primarily this is to get CI working on forks again (after the generated deepcopy code was removed from the repo), although also some general-goodness changes included.
* Actually move the cloned repo to the desired directory (bluek8s/kubedirector) rather than just making a symlink. At one point I thought this was needed to fix some operator-sdk behavior, now I'm not sure, but things work so I'm going to leave it this way.
* Don't do "make dep" (which does "dep ensure -v -update"); just do "dep ensure -v".
* Move some stuff from before_install into the install step. Partly just because these things make sense there, but also because if we don't define the install step, the default install step (which runs travis_install_go_dependencies) tries to do things that depend on the generated …
=> fixes for CI

pkg/controller/kubedirectorcluster/types.go
issue #210
Spots where we need to chain commands with && instead of using semicolon, so that a command failure gets propagated.
=> don't ignore command errors

HISTORY.md, doc/kd-release-process.md, doc/quickstart.md, version/version.go
This will be merged to master AFTER the v0.3.0 release tag has been created (to point to the 0.3.0 release-point commit).
In the changelog I've dated the release for tomorrow (the 16th) so that the 0.3.0 image can be test-soaked for a bit.
=> advertise the 0.3.0 release

deploy/example_configs/cr-config-onprem.yaml, deploy/kubedirector/kubedirector_v1alpha1_kubedirectorconfig_crd.yaml, pkg/apis/kubedirector.bluedata.io/v1alpha1/kubedirectorconfig_types.go, pkg/catalog/configmeta.go, pkg/controller/kubedirectorcluster/members.go, pkg/shared/globalconfig.go, pkg/shared/types.go, pkg/triple/triple.go, pkg/validator/config.go, pkg/validator/util.go
Fix for issue 
https://github.com/bluek8s/kubedirector/issues/57
I didn't want to use /etc/resolv.conf. We have to rely on the format populated by k8s, which is kind of fragile. So ended up changing the Config CRD, so user can define the actual domain. Also when we create the mutating webhook we don't need to use a full domain name for creating the self-signed cert.
=> support any cluster domain

Gopkg.lock, deploy/example_catalog/cr-app-cdh5142cm.json, deploy/example_configs/eks-gp2-for-kd.yaml, deploy/kubedirector/kubedirector_v1alpha1_kubedirectorapp_crd.yaml, deploy/kubedirector/kubedirector_v1alpha1_kubedirectorcluster_crd.yaml, deploy/kubedirector/kubedirector_v1alpha1_kubedirectorconfig_crd.yaml, deploy/kubedirector/rbac-default.yaml, doc/eks-notes.md, doc/gke-notes.md, doc/quickstart.md, pkg/apis/kubedirector.bluedata.io/v1alpha1/kubedirectorapp_types.go, pkg/apis/kubedirector.bluedata.io/v1alpha1/kubedirectorcluster_types.go, pkg/apis/kubedirector.bluedata.io/v1alpha1/kubedirectorconfig_types.go, pkg/controller/kubedirectorcluster/cluster.go, pkg/controller/kubedirectorconfig/config.go, pkg/executor/guest.go, pkg/executor/statefulset.go, pkg/executor/types.go, pkg/executor/util.go, pkg/observer/doc.go, pkg/shared/kubedirectorobject.go, pkg/shared/types.go, pkg/validator/cluster.go
Significant improvements to the CRDs to make them check more stuff and to get rid of errors reported by K8s on the created CRD resources. These changes do require using the "nullable" attribute, which in turn requires using K8s 1.14 or later. Also we need to be more careful about when we specify "omitempty" for our type fields.
Use the API rbac.authorization.k8s.io/v1 instead of rbac.authorization.k8s.io/v1beta1. This non-beta version has been available for a long time and beta may go away.
Improvements to the GKE and EKS usage notes.
Some significant changes to how we handle finalizers in our CR reconciliation handlers. The previous logic relied on the first creation of the finalizer happening before any status stanza existed (so that status protection would not be triggered by the …
=> omnibus of improvements from work on other forks

deploy/kubedirector/kubedirector_v1alpha1_kubedirectorapp_crd.yaml, pkg/catalog/interrogate.go, pkg/catalog/types.go, pkg/executor/service.go, pkg/executor/util.go
We don't make use of urlScheme much in the example apps yet, but this will be handy for clients.
If urlScheme is unspecified just prepend "generic-".
=> prepend urlScheme to port names in created member services

deploy/kubedirector/kubedirector_v1alpha1_kubedirectorcluster_crd.yaml, pkg/apis/kubedirector.bluedata.io/v1alpha1/kubedirectorcluster_types.go, pkg/executor/service.go, pkg/executor/statefulset.go, pkg/executor/types.go, pkg/executor/util.go, pkg/validator/cluster.go
Add serviceLabels to the role config too, to allow specifying labels for services related to the role.
Also a couple of slight tweaks to existing label behavior:
- Don't put the user-specified pod member labels on the statefulset; only on the pods.
- Go easier on the labels in the pod selector in a member service; just reference the pod name.
=> user-specified labels feature tweaks

pkg/executor/statefulset.go, pkg/executor/types.go
We don't inject config meta in the container if app config is not required. So drop in a file (kubedirector.init) for initContainer check.
=> InitContainer should not rely on configmeta.json

deploy/kubedirector/deployment-prebuilt.yaml, deploy/operator.yaml, doc/gke-notes.md, pkg/validator/server.go, pkg/validator/types.go, pkg/validator/util.go
We should never let an invalid CR into etcd. This will totally screw up any further reconciliation attempts. So, K8s should reject an attempt to create/modify (or in some cases even an attempt to delete) one of our CRs if our admission control hook is down. To ensure this, I've changed the failure policy to "Fail" for our webhooks. (issue #204)
In the event that someone really needs to delete a CR and KD is down and can't be resurrected, then they will have to edit or remove the webhook.
I've also added a liveness probe. If our validation server is down (probably because the entire operator process is dead), K8s will restart the container after 30 seconds of dead-ness. This should also help to solve the issue where the operator binary isn't running inside the container after a host reboot …
=> robustification

pkg/executor/statefulset.go
Noticed few issues with the Lifecycle poststart hook
- Poststart script run as the container user. So we can't that /etc/ is writable. So don't create the temp file to /etc/. Instead use /tmp
- Noticed couple of times, that /etc/resolv.conf is empty briefly and then it gets loaded with actual data. Lets wait for a non-empty /etc/resolv.conf
- Also added some extra logging
=> Making poststart robust

Makefile, cmd/manager/main.go, pkg/controller/kubedirectorcluster/cluster.go, pkg/controller/kubedirectorcluster/kubedirectorcluster_controller.go, pkg/controller/kubedirectorcluster/members.go, pkg/controller/kubedirectorcluster/roles.go, pkg/controller/kubedirectorcluster/types.go, pkg/controller/kubedirectorconfig/config.go, pkg/controller/kubedirectorconfig/kubedirectorconfig_controller.go, pkg/executor/cluster.go, pkg/executor/service.go, pkg/executor/statefulset.go, pkg/executor/volume.go, pkg/observer/observer.go, pkg/shared/client.go, pkg/validator/util.go
Includes at least some amount of fixing or workaround for issue #265 and issue #267.
Each commit is its own self-contained thing with its own description. Bundling them together here for quicker testing and less build churn.
It's probably easiest to examine each commit individually, especially because https://github.com/bluek8s/kubedirector/commit/7b4744f8ff86b66c4b5e5a126e926598baab8e72 changes a lot of files mechanically through find-and-replace (only the client.go changes in there are interesting).
=> collection of fixes

deploy/kubedirector/kubedirector_v1beta1_kubedirectorcluster_crd.yaml, doc/virtual-clusters.md, pkg/apis/kubedirector.hpe.com/v1beta1/kubedirectorcluster_types.go, pkg/controller/kubedirectorcluster/cluster.go, pkg/controller/kubedirectorcluster/members.go, pkg/controller/kubedirectorcluster/roles.go, pkg/controller/kubedirectorcluster/types.go, pkg/controller/kubedirectorconfig/config.go, pkg/executor/guest.go, pkg/validator/cluster.go, pkg/validator/types.go
This PR addresses (at least partially) issue #18 and issue #66.
We want to add more status useful for analyzing when cluster members are in bad or transitional states, and add more smarts to reconciliation to help cluster members survive those states.
Note that this change does NOT include automatic recovery if the host for some member is permanently down. Someone with the right privileges will still need to explicitly delete that pod so that the statefulset controller will reschedule/recreate it. There is room for us to add value there in the future.
If a member is stuck in config-error state, you can also delete its pod to trigger another attempt at getting that member set up. (If there's a bug in your app image/setup it will probably just end up in config-error state again though.) …
=> handle host/pod shutdown and reboot

deploy/example_catalog/cr-app-cdh5142cm.json, deploy/example_catalog/cr-app-centos7.json, deploy/example_catalog/cr-app-spark221e2.json, deploy/example_catalog/cr-app-tensorflow-notebook.json, doc/gke-notes.md
Addresses HAATHI-15046:
* The "short names" really should be short.
* In the CentOS app, say exactly what OS version it is.
* Fix some capitalizations for identifiers like Jupyter and TensorFlow.
* In the TensorFlow app, the distroID should be some unique ID that is namespaced with the name of the "packager", which in this case is us. Still using the "bluedata" packager identity for now.
* Also in the TensorFlow app, the version needs to be a semantic version string tracking the evolution of this particular CR.
Also taking this opportunity to massage the GKE notes a bit. Still fiddling with the way to describe cluster version selection.
=> App tweaks

pkg/catalog/interrogate.go, pkg/executor/statefulset.go, pkg/executor/types.go
This change is intended as at least a partial fix for the issue, https://github.com/bluek8s/kubedirector/issues/263.
The NVIDIA-suggested workaround (https://github.com/NVIDIA/k8s-device-plugin/issues/87), referred to by the issue's description, is implemented:
For each container pertaining to a Role that has NOT requested a GPU resource, an "NVIDIA_VISIBLE_DEVICES=VOID" environment variable is added.
We may have to watch for future updates to NVIDIA's Docker plug-in, to see if the need for this workaround is removed.
=> Kishore test

pkg/controller/kubedirectorcluster/types.go
If nothing is specified, nohup redirects it's stdout to a file named nohup.out. We were trying to redirect the stdout and stderr of the _command_ running with nohup, but not of nohup _itself_ . As a result, starscripts writing to stdout/stderr in the pods was not getting redirected to configure.* files as originally intended and app developers have to take care of writing logs in their own custom files. 
Testing done on a simple [Helloworld KD APP](https://github.com/bluedatainc/bluedata-catalog/tree/ritesh-kd-helloworld/helloworld).
=> Fix appconfig logging to log to configure.* files

deploy/kubedirector/kubedirector.hpe.com_kubedirectorclusters_crd.yaml, pkg/apis/kubedirector/v1beta1/kubedirectorcluster_types.go, pkg/catalog/configmeta.go, pkg/catalog/types.go, pkg/controller/configmap/configmap.go, pkg/controller/kubedirectorcluster/cluster.go, pkg/controller/kubedirectorcluster/types.go, pkg/controller/secret/doc.go, pkg/controller/secret/secret.go, pkg/controller/secret/secret_controller.go, pkg/observer/observer.go, pkg/shared/types.go, pkg/validator/cluster.go
- Currently, cluster connections utilizes **connectionsGenerationToProcess** in spec to determine if connections have been updated or not. 
- It's not ideal to use a field in spec for implementation purpose and hence, removed from the spec.
- The decision of whether connection object or the actually connected resources were modified is now determined by the md5 checksum of resource versions of connected k8s resources. This checksum is stored in the cluster's status object.  
- Also added secret as one of the connectable resources similar to clusters and configmaps.
- Modified reconciler for configmap to not change the cluster's spec but to invoke the cluster's reconciler by updating annotation.
- Secret's reconciler is similar to configmap.
=> Cluster connections refactoring and addition of secret as connectable resource

deploy/example_catalog/cr-app-cdh632cm.json, pkg/apis/kubedirector/v1beta1/kubedirectorapp_types.go, pkg/controller/kubedirectorcluster/cluster.go, pkg/controller/kubedirectorcluster/members.go
* **Don't update LastSetupGeneration too early.** If there are any members currently in transitional state, they might be on the way to generate additional notifies related to this gen on future handler passes. So don't update LastSetupGeneration until all members have exited transitional state. Fixes #308 . Should be backported to 0.4.2.
* **Update spec gen for member add/remove.** It was incrementing only for connections changes and not for other changes. (Also, we don't need to do atomic int operations to increment it.)
* **Fix defaultEventList.** A typo in the JSON tag for defaultEventList meant that our internal DefaultEventList field was never populated, always nil.
* **Correctly honor eventList.** When queuing notifies, the code was checking the event list for the role of the …
=> notifications fixes

pkg/controller/kubedirectorcluster/cluster.go, pkg/controller/kubedirectorcluster/members.go
fixes #315 
Seems that there can be a startup race before systemd services can be properly started inside nodes. Noticing this on K8s nodes that use docker-ce. So let's be cautious and not run startscripts until systemd is working (for apps that require it).
Also a fix in cluster.go here for something that golint was complaining about.
Should backport this to 0.4.2.
=> ensure systemd is up before service enable/start

deploy/example_catalog/cr-app-mapr610-secured.json, deploy/example_catalog/cr-app-mapr610-unsecured.json, deploy/example_clusters/cr-cluster-mapr610.yaml
MapR app on KD version 1.0
- This version of the app is designed for KD and also each services is made to run independent pods, while in EPIC few services were grouped
- There is no need for repo location because all the required services are already installed on docker file, based on pod respective services gets enabled and configured
- As per the requirement for 5.1, it was decided to have only MapR core functionality, Hive, Hue and Edge services.
- Through secrets user can change the default MapR admin password and also pass the ssl_truststore and mapr-clusters.conf information to the pod (currently provided as a workaround). Until this feature gets in KD.
- There are 2 dockerfiles one for MEP and other one for edge pod. The reason for having 2 is because few packages cannot co-exist, …
=> MapR 6.1 MEP 6.3 KD app

deploy/example_catalog/cr-app-elk771.json
This fixes the issue https://github.com/bluek8s/kubedirector/issues/335 regarding autostart of services when pods are deleted. Updated the image version to 1.1
Enabled elasticsearch, kibana and logstash with systemctl.
=> ELK 771 update version of elk app json for autostart of services.

deploy/example_catalog/cr-app-cdh632cm.json
This fixes https://github.com/bluek8s/kubedirector/issues/335 
Enabled services cloudera-scm-server, cloudera-scm-agent and mysqld so that they auto restart when pod is deleted. The app setup change PR for reference is   https://github.com/bluedatainc/bluedata-catalog/pull/389
=> cdh632 update version to 1.2

pkg/controller/kubedirectorcluster/cluster.go, pkg/validator/cluster.go, pkg/validator/types.go
Introduce a limit on the number of total members for a KD cluster.
Change the statusChange flag to false in case the cluster is being
deleted and update write back fails.
=> KD Issues 336 and 337

deploy/example_clusters/cr-cluster-cdh632cm-stor.yaml, deploy/example_clusters/cr-cluster-elk771.yaml
Added members: 1 for optional roles in cdh cluster yaml and elk cluster yaml. We will need to pass members key so that roles get created when cluster is created since the cardinality of these roles is 0+ and it considers minimum of 0 unless members key is specified.
=> CDH and ELK add members key for optional roles.

deploy/example_catalog/cr-app-cdh632cm.json
Following recent changes for dtap in kubedirector, made corresponding changes in app for dtap and bumped up the version to 1.3
Reference pull request in app:
https://github.com/bluedatainc/bluedata-catalog/pull/395
=> cdh632 update version to 1.3 for dtap

deploy/example_catalog/cr-app-spark245.json
Spark245:v1.7 is updated as per the changes done for dtap.
As per new changes dtap, /opt/bdfs folder created and bluedata-dtap.jar file placed by default. Spark245 start script is updated as per the changes.
Reference:
https://github.com/bluedatainc/bluedata-catalog/pull/382/commits/20a90bcc7c24bf9ec36b319763aedc3fc2b73974
=> Spark245:v1.7 is updated as per the changes done for dtap.

pkg/validator/app.go, pkg/validator/types.go
closes issue #319
It's not super-trivial to see whether an incoming spec changes anything, because of the way we handle global defaults and apply them to roles. So the validateRoles function here is changed to not only generate patches to modify the resulting document, but also apply the same changes to the in-memory appCR so we can use it for comparisons if this is a PUT.
Then admitAppCR does the comparison.
There's a big comment added to admitAppCR so more about that below...
==========
This change also fixes a minor bug in our defaults handling. The pattern is that we apply the global default to the roles (if necessary) and then remove the default from the spec. However in the case of defaultConfigPackage, if it was explicitly set to null, we were not removing it.
Among our own example …
=> allow PUT to an in-use kdapp if nothing in the spec is being changed

deploy/example_catalog/cr-app-cdh632cm.json
Updated version of cdh 632 app after changes in configmap data structure.
Below is pull request in bluedata-catalog 
https://github.com/bluedatainc/bluedata-catalog/pull/395
=> CDH 632 update version of app after change in configmap structure

deploy/example_catalog/cr-app-spark245.json
Spark245:v1.8 is updated in jupyterhub-config.py as per new Json tree structure is changed in Connection feature.
Reference:
https://github.com/bluedatainc/bluedata-catalog/pull/411
=> Spark245:v1.8 is updated as per new Json tree structure in Connection feature

pkg/catalog/configmeta.go, pkg/controller/configmap/configmap.go, pkg/controller/kubedirectorcluster/cluster.go, pkg/controller/secret/secret.go
This PR tackles the deletion of the connected cluster, because of which KD was panicking into an unrecoverable state.
Example:
Cluster A's connection
```
connections:
clusters:
- "clusterB"
``` 
If clusterB is deleted then KD was panicking while trying to calculate clusterB's configmeta.
Added the required checks to avoid such scenarios.
=> Cluster Connection deletion fix

go.mod, go.sum
See issue #370 for details.
Note that this change does not affect the generated binary, so the removed dependency was not being used/shipped in the operator.
(A couple of unused dependencies were also dropped in the process.)
=> remove dependency on unlicensed code

pkg/executor/statefulset.go
Might have characters in it that are invalid for volume name.
closes #387 
@swamibluedata any possible issue with this?
=> don't use CR name in volume name

Makefile
This can be done once a new release of configcli has been made.
=> Bump configcli version for compatibility with python3.

deploy/kubedirector/kubedirector.hpe.com_kubedirectorapps_crd.yaml, pkg/apis/kubedirector/v1beta1/kubedirectorapp_types.go
https://github.com/bluek8s/kubedirector/issues/423
Add a field to the app crd where we can store URL path for logos associated with a specific app.
=> App Logos [Issue #423]

deploy/kubedirector/kubedirector.hpe.com_kubedirectorclusters_crd.yaml, pkg/apis/kubedirector/v1beta1/kubedirectorcluster_types.go, pkg/catalog/configmeta.go, pkg/catalog/types.go, pkg/controller/kubedirectorcluster/cluster.go, pkg/controller/kubedirectorcluster/roles.go, pkg/executor/statefulset.go, pkg/executor/types.go
- Implementation for issue #444
- Support to mount block devices.
- If such block device(s) is/are mounted, add the mount path(s) in appconfig JSON
- Fix #442  
The Cluster Spec is updated to have `BlockStorage` field which takes `prefixPath`, `numDevices`, and `storageClassName` for mounting block(s) to the role's statefulset. `size` is an optional parameter and a default size of `1Gi` is set if it is not specified. 
`storageClassName` will be used to bind an appropriate PV. The `PV` and `StorageClass` need to be created before launching a KDApp with block devices. 
~~Currently, the code supports one deviceVolume which is commensurate with volume mount support.~~ The code now supports mounting multiple blocks. `numDevices` reads the number of blocks required, and `prefixPath` reads the …
=> Add volumeDevice support for KDApps

deploy/example_catalog/cr-app-datafabric610.json, deploy/example_catalog/docs/datafabric610-readme.md, deploy/example_catalog/docs/dfcompute610-readme.md, deploy/example_clusters/cr-cluster-datafabric610.yaml
Datafabric 610 app creates a basic MapR Cluster with facility to run YARN jobs and also has support to Oozie. The minimal cluster will have 4 roles
- cldb: This runs MapR CLDB service, Zookeeper and MapR Fileserver services. 
- control-system: This runs MapR Control System, Zookeeper and YARN History Server
- resource-manager: This runs YARN Resource Manager and Zookeeper 
- nodemanager: This runs YARN Nodemanager and MapR Fileserver. 
There are 2 optional roles also available
- oozie: This runs oozie services
- edge: This is MapR Client to work as a client for Datafabric app.
The special feature in this version of the app is, facility to use the raw disks which is presented to the pod. CLDB and Nodemanager requires disk storage. The disk storage can be raw disk or flat-file based disk. …
=> Added Datafabric610 to kubedirector

deploy/example_catalog/cr-app-kafka55.json, deploy/example_catalog/docs/kafka55-readme.md, deploy/example_clusters/cr-cluster-kafka55-stor.yaml
EZEPIC-22 - Need to rename "Confluent Kafka" in the app store - equivalent changes in KD App for Confluent Platform:
Changes done on App json, Cluster yaml definitions and documentation to reflect Confluent Platform instead of Confluent Kafka in app description
=> Bluek8s ConfluentKafka app name changed to ConfluentPlatform

.gitignore, deploy/kubedirector/kubedirector.hpe.com_kubedirectorclusters_crd.yaml, pkg/apis/kubedirector/v1beta1/kubedirectorcluster_types.go, pkg/executor/statefulset.go
As requested in issue #48:
- add Affinity field to KDCluster's Role spec
- use it to define affinity for corresponding StatefulSet
- update CRDs
=> #48 Allow specifying Affinity for roles

deploy/example_catalog/cr-app-ngc.yaml, deploy/example_clusters/cr-cluster-ngc.yaml, deploy/kubedirector/kubedirector.hpe.com_kubedirectorapps_crd.yaml, pkg/apis/kubedirector/v1beta1/kubedirectorapp_types.go, pkg/catalog/interrogate.go, pkg/executor/statefulset.go, pkg/validator/app.go, pkg/validator/types.go
A lot of applications like NVIDIA NGC require tty and stdin for the pod. This feature lets App developer specify that in the kdapp spec. Also added the Nvidia NGC app in the catalog
https://github.com/bluek8s/kubedirector/issues/461
=> Override STDIN and TTY in Role Spec for KDApp 

pkg/controller/kubedirectorcluster/members.go
This issue is encountered in the following scenario:
When a KD Cluster does not contain `lastConnectionVersion` member status (will be typically found in v0.5.1 and below) and the connections are updated. This leads to `handleReadyMembers()` checking for the `memberVersion` (which is nil) and as a result, KD goes in panic state. 
`handleReadyMembers()` gets called only when we are operating on ready members. Currently, it is called to inject configmeta initially and thereafter, every time the connections are modified. We also use this function to call startscript with --reconnect flag only if the connections are modified. 
In the scenario when the deref is encountered, the only possible way to enter `handleReadyMembers()` is when connections are modified. (since the KDCluster is already …
=> Fix #467 - nil deref in HandleReadyMembers

pkg/controller/kubedirectorcluster/cluster.go, pkg/controller/kubedirectorconfig/config.go, pkg/validator/app.go, pkg/validator/cluster.go, pkg/validator/config.go
There are situations where a client is not allowed to change a role spec: if the previous change is still being processed, or if the role has nonzero member count.
As per issue #466 though, there are some cases where a resource quantity is getting its format changed, e.g. from "0.5" to "500m", without its quantity actually being changed. Sometimes this is even happening as part of a status write from KD itself. We're not explicitly asking for this format change -- something along the way in client-go or K8s is doing it -- but whatever the reason, we need to allow it to happen.
So this change to how we handle checking for CR changes is motivated by issue #466, but really it applies everywhere we do such a check.
Along with general regression-test creations of existing kdapp types while …
=> resource quantity format changes shouldn't trigger "spec has changed" check

pkg/controller/kubedirectorcluster/types.go
Minor tweaks to appPrepConfigRunCmd to fix stderr and status which was getting lost.
Even a failed startscript was not writing anything to /opt/guesstconfig/configure.stderr or /opt/guesstconfig/configure.status.
Tested all /opt/guestconfig/configure.* for successful and unssucessful runs of startscript.
=> Fix appPrepConfigRunCmd to report stderr and status

deploy/kubedirector/kubedirector.hpe.com_kubedirectorclusters_crd.yaml, deploy/kubedirector/kubedirector.hpe.com_kubedirectorconfigs_crd.yaml, go.mod, go.sum, pkg/apis/kubedirector/v1beta1/kubedirectorcluster_types.go, pkg/apis/kubedirector/v1beta1/kubedirectorconfig_types.go, pkg/executor/service.go, pkg/executor/statefulset.go, pkg/executor/util.go, pkg/shared/globalconfig.go, pkg/validator/cluster.go, pkg/validator/config.go, pkg/validator/util.go
Allow user-specified annotation in the same way we allow user-specified labels.
Also, let the KD global config specify labels/annotations that will be applied to any pod or member service.
A specific use case for this is to control Velero backups, where we NEVER want Velero to try to back up the tmpfs volumes of KD-created pods. With this change, you can use the global config to specify the following pod annotation to achieve that: backup.velero.io/backup-volumes-excludes: tmpfs-tmp,tmpfs-run,tmpfs-run-lock
=> More control over labels and annotations

deploy/kubedirector/kubedirector.hpe.com_kubedirectorapps_crd.yaml, pkg/apis/kubedirector/v1beta1/kubedirectorapp_types.go, pkg/catalog/interrogate.go, pkg/validator/app.go, pkg/validator/cluster.go, pkg/validator/types.go
closes issue #536
If an app is going to use persistent storage, it probably has a size that is the minimum necessary for the app to be successfully brought up. Let's express that.
When the kdcluster asks for resources, persistent storage is in a different section than other resources (for reasons having to do with how these requests get expressed in K8s resources). We'll have a parallel construction in the kdapp here... the new minStorage optional object in a role definition will be parallel to minResources.
Omitting minStorage means that a role doesn't care whether you give it a PV, and if you do give it a PV, it doesn't care what size it is. Generally this should only be omitted for a truly ephmereal role.
If minStorage is specified, you have to provide a size property (with a value in …
=> allow kdapp to specify min persistent storage size

Makefile
Quick-fix for the Makefile deploy target problem, when application examples are started to deploy but `kubectl-validator` service is not ready, which causes the error:
`Error from server (InternalError): error when creating "deploy/example_catalog/cr-app-cassandra-3.11.json": Internal error occurred: failed calling webhook "hard-validate-cr.kubedirector.hpe.com": Post "https://kubedirector-validator.hpecp.svc:443/validate?timeout=30s": service "kubedirector-validator" not found`
=> Added pause until validator service start

Makefile, build/Dockerfile, deploy/example_catalog/cr-app-cassandra-3.11.json, deploy/example_catalog/cr-app-jupyter-notebook.json, deploy/kubedirector/kubedirector.hpe.com_kubedirectorapps_crd.yaml, doc/app-filesystem-layout.md, doc/gke-notes.md, pkg/apis/kubedirector/v1beta1/decode.go, pkg/apis/kubedirector/v1beta1/kubedirectorapp_types.go, pkg/catalog/interrogate.go, pkg/controller/kubedirectorcluster/members.go, pkg/controller/kubedirectorcluster/types.go, pkg/executor/statefulset.go, pkg/shared/types.go, pkg/validator/app.go
This change allows a kdapp resource to opt-in to a different filesystem layout which can make PV initialization much faster.
The best functional description is in the new app-filesystem-layout.md doc contained in this changelist.
The Makefile change here is tangentially related; since a new configcli package is used, I want the build process to make sure that it will get the new configcli if the currently downloaded package is not the right one.
I'll add some other notes as code comments in the changes.
====================
A quick example of the benefits of the new layout. One my usual test system (granted, VMs with slow I/O) launching jupyter notebook with a PV can take hours with the old layout. With the new layout, less than a minute.
=> issue #537: prune down the default persist dirs

doc/app-filesystem-layout.md, pkg/controller/kubedirectorcluster/members.go
This allows for an intermediate step of app development if an app needs to adopt the new persistent dirs layout but would be broken by the new more restrictive perms on /etc/guestconfig. This lets the startscript be explicit about the need/desire to share configmeta.json with other user accounts, without KD interfering.
The functional change in KD is that we will only set the 700 perms on /etc/guestconfig when first creating that directory and configmeta.json; we'll no longer re-set the perms each timme configmeta.json is updated.
=> allow startscript to open the /etc/guestconfig perms

pkg/executor/statefulset.go
closes #565 
There's no benefit to and sometimes problems from specifying different resources for the init container vs. the app container.
=> set init resources same as app resources

deploy/example_catalog/cr-app-deployment-engine.json, deploy/example_catalog/cr-app-jupyter-notebook.json, deploy/example_catalog/cr-app-training-engine.json, deploy/kubedirector/kubedirector.hpe.com_kubedirectorapps_crd.yaml, deploy/kubedirector/kubedirector.hpe.com_kubedirectorclusters_crd.yaml, deploy/kubedirector/kubedirector.hpe.com_kubedirectorconfigs_crd.yaml, deploy/kubedirector/kubedirector.hpe.com_kubedirectorstatusbackups_crd.yaml, doc/eks-notes.md, doc/quickstart.md, doc/upgrade.md, pkg/observer/observer.go, pkg/validator/app.go, pkg/validator/cluster.go, pkg/validator/config.go, pkg/validator/pvc.go, pkg/validator/server.go, pkg/validator/types.go, pkg/validator/util.go
closes issue #504
* Moved to v1 instead of v1beta1 for apiextensions.k8s.io and admissionregistration.k8s.io.
* We can now run on K8s 1.22 and beyond, but our K8s support floor is raised to 1.16.
* CRs can no longer have non-schema-approved fields, except in locations where we explicitly approve that behavior (as in resource requirements, to support K8s extended resources).
* Didn't change the AdmissionReview/AdmissionResponse versions quite yet; we don't need to (yet), and there are some issues there to untangle. Did mark that module with a unique import alias "av1beta1" to more easily find and change them in the future.
* Updated docs accordingly.
=> deal with some deprecated API

deploy/kubedirector/kubedirector.hpe.com_kubedirectorclusters_crd.yaml, deploy/kubedirector/kubedirector.hpe.com_kubedirectorconfigs_crd.yaml, deploy/kubedirector/kubedirector.hpe.com_kubedirectorstatusbackups_crd.yaml
issue #611
In the v1 schema regime, the contents of these objects were being discarded.
In the case of the kdstatusbackup, this copy-and-paste of the status schema is not a great solution for long-term development/maintenance (since any future status schema changes now have to be made in two places), but it's a good and easily-verified-as-correct fix for the immediate issue. Will explore other solutions in a following KD release.
=> fix incomplete schema areas

deploy/kubedirector/kubedirector.hpe.com_kubedirectorclusters_crd.yaml, pkg/apis/kubedirector/v1beta1/kubedirectorcluster_types.go, pkg/controller/kubedirectorcluster/cluster.go, pkg/controller/kubedirectorcluster/members.go, pkg/controller/kubedirectorcluster/roles.go, pkg/executor/statefulset.go, pkg/shared/util.go, pkg/validator/cluster.go
Resolves https://github.com/bluek8s/kubedirector/issues/595
1. Extracted `RoleStatus` management from `executor` to `controller` package
2. Corrected `upgradeInfo` object elimination. Before removing the object cluster should check, if there was a rollback then all role upgrade statuses should be set to `RolledBack` value or should stay empty, if a corresponding role was not changed by the last upgrade. Possibly it should also resolve https://github.com/bluek8s/kubedirector/issues/594
When upgradeInfo is removed and upgrade process is finished, all the role upgrade statuses are set to `RoleConfigured` (default empty value), which partially resolves https://github.com/bluek8s/kubedirector/issues/593
3. As currently we don't need to use a new image value stored in `UpgradingMembers` map, it …
=> Extracted role status management to controller package

pkg/executor/cluster.go, pkg/executor/statefulset.go, pkg/executor/types.go
Testing is in progress -- getting this up now for an initial look by @Kosta91 .
Previously the code was checking to see if rsync was available here. Technically we should really use generateRsyncInstalledCmd for the test rsync cmd there, if using that approach -- that would make it match up exactly with the initial decision of whether or not to use rsync.
However, instead of making that fix, let's cut to the chase and just check for the existence of the progress file that we're about to try to read.
(Also fixed a typo.)
=> slightly different approach to testing for progress data

pkg/executor/statefulset.go, pkg/executor/types.go, pkg/validator/cluster.go, pkg/validator/types.go
Fixes 
https://github.com/bluek8s/kubedirector/issues/555
During validation, generate all system generated volumes. Use this to match it against provided Volume Projections. If there is a clash in mountPath report an error.
Use an existing function generateVolumeMounts.
=> Duplicate mountPath validation

.travis.yml, CONTRIBUTING.md, Makefile, doc/kubedirector-development.md, go.mod, go.sum
Posting a draft PR of this for CI purposes. Still needs testing.
----------
Putting some CVEs in our rearview mirror.
jf docker scan before: 4 critical, 15 high
after (using golang 1.18.5): 1 critical, 8 high
The remaining critical is CVE-2022-1996 from emicklei/go-restful ... we could try to force an update on that package or we might be required to finally move to a more recent version of operator SDK. I'm not super exercised about that one though because I believe it does not apply to KD. Will double-check.
=> require golang 1.18

deploy/kubedirector/kubedirector.hpe.com_kubedirectorclusters_crd.yaml, deploy/kubedirector/kubedirector.hpe.com_kubedirectorconfigs_crd.yaml, pkg/apis/kubedirector/v1beta1/kubedirectorcluster_types.go, pkg/apis/kubedirector/v1beta1/kubedirectorconfig_types.go, pkg/executor/statefulset.go, pkg/shared/client.go, pkg/shared/globalconfig.go, pkg/validator/cluster.go, pkg/validator/types.go
The memory backing /dev/shm in a container is normally limited to 64MB. Some applications need (a lot) more than that, e.g. PyTorch jobs.
At a glance it seems like a solution would be to mount an emptyDir memory volume to /dev/shm. However until (somewhat) recently you couldn't specify the max size of such a volume, and it would be half of your host's RAM. That's ... not good.
K8s 1.20 add a feature flag (false by default) to enable setting a size limit on such volumes. With K8s 1.22, that feature flag is true by default. If all goes well it should eventually graduate out of feature-flag-land but hasn't yet.
=====
This change introduces an optional quantity for role spec in a kdcluster: "sharedMemory". So for example your kdcluster role spec could include
```yaml
sharedMemory: "1Gi"
``` …
=> support custom size for /dev/shm
